# Generated by Django 4.1.7 on 2023-03-27 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppAscenzi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='publisher',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
