# Generated by Django 4.1.7 on 2023-03-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAscenzi', '0002_juguete_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='juguetes'),
        ),
    ]
