# Generated by Django 4.1.7 on 2023-03-29 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppAscenzi', '0005_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
